pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "my-spring-boot-app:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Build Docker image
                    docker.build(DOCKER_IMAGE)
                }
            }
        }
        stage('Cleanup') {
            steps {
                script {
                    // Remove Docker image after build
                    docker.image(DOCKER_IMAGE).remove()
                }
            }
        }
    }
}
