pipeline {
     agent any

    tools {
        // Specify the Maven installation
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from GitHub repository
                git branch: 'main', credentialsId: 'f5fe8d92-8d03-465f-9d5d-6c052451abde', url: 'https://github.com/vk23191/JenkinsDockerSpringBoot.git'
            }
        }

         stage('Build Docker Image') {
            steps {
                // Build Docker image
                sh 'docker build -t my-app .'
            }
        }

        stage('Deploy to Docker') {
            steps {
                // Push Docker image to registry (if needed)
                // sh 'docker push your-registry/my-app'

                // Run Docker container
                sh 'docker run -d --name my-app -p 8080:8080 your-image-name'
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! This can include additional notifications or steps upon success.'
        }
        failure {
            echo 'Pipeline failed! This can include cleanup or notifications upon failure.'
        }
    }
}